// <auto-generated />
using System;
using System.Collections.Generic;
using AniMatcher.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AniMatcher.DataAccess.Migrations
{
    [DbContext(typeof(AniMatcherContext))]
    [Migration("20250414141947_FixingRelations")]
    partial class FixingRelations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AniMatcher.Domain.Character", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CopyrightId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Names")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("CharacterId");

                    b.HasIndex("CopyrightId");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            CharacterId = new Guid("2d711253-bddf-4f68-b697-c77fe3925897"),
                            CopyrightId = new Guid("b14a485d-dca4-48b6-a524-a361bc0745e9"),
                            Name = "Batman",
                            Names = "[\"бэтмэн\",\"бэтмен\",\"batman\"]"
                        },
                        new
                        {
                            CharacterId = new Guid("ba7f730f-d24c-46b4-a544-75653a741ddb"),
                            CopyrightId = new Guid("b14a485d-dca4-48b6-a524-a361bc0745e9"),
                            Name = "Superman",
                            Names = "[\"superman\",\"супермен\",\"супермэн\"]"
                        },
                        new
                        {
                            CharacterId = new Guid("e8d37f9f-0897-4dee-80f3-cc6fc9e7669c"),
                            CopyrightId = new Guid("b14a485d-dca4-48b6-a524-a361bc0745e9"),
                            Name = "Flash",
                            Names = "[\"flash\",\"флэш\"]"
                        },
                        new
                        {
                            CharacterId = new Guid("99984987-d958-4db6-a0ed-746ca54c6443"),
                            CopyrightId = new Guid("5073af1b-9c3c-4766-ae62-f9253aaf0afb"),
                            Name = "Hulk",
                            Names = "[\"hulk\",\"халк\"]"
                        },
                        new
                        {
                            CharacterId = new Guid("f8e08483-d7ea-4821-affa-5c133a1390cf"),
                            CopyrightId = new Guid("5073af1b-9c3c-4766-ae62-f9253aaf0afb"),
                            Name = "Spider Man",
                            Names = "[\"человек-паук\",\"человек паук\",\"spider-man\",\"spider man\"]"
                        },
                        new
                        {
                            CharacterId = new Guid("71e7e9a9-cc8c-4325-8b0a-daa181748ffc"),
                            CopyrightId = new Guid("5073af1b-9c3c-4766-ae62-f9253aaf0afb"),
                            Name = "Iron Man",
                            Names = "[\"iron man\",\"ironman\",\"железный человек\"]"
                        },
                        new
                        {
                            CharacterId = new Guid("1c49af7b-39cb-4ef2-b3d4-6cc22482a6c9"),
                            CopyrightId = new Guid("515ac11d-55a1-4e4b-8364-6543cd6e6154"),
                            Name = "Naruto",
                            Names = "[\"наруто\",\"naruto\"]"
                        },
                        new
                        {
                            CharacterId = new Guid("478e70a1-123c-49c5-b13c-86fee3cc4a6d"),
                            CopyrightId = new Guid("515ac11d-55a1-4e4b-8364-6543cd6e6154"),
                            Name = "Sasuke",
                            Names = "[\"саске\",\"сасуке\",\"sasuke\"]"
                        },
                        new
                        {
                            CharacterId = new Guid("644c95b3-8c11-4262-a07c-894e45cb104f"),
                            CopyrightId = new Guid("515ac11d-55a1-4e4b-8364-6543cd6e6154"),
                            Name = "Sakura",
                            Names = "[\"sakura\",\"сакура\"]"
                        });
                });

            modelBuilder.Entity("AniMatcher.Domain.Franchise", b =>
                {
                    b.Property<Guid>("FranchiseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Names")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("FranchiseId");

                    b.ToTable("Franchises");

                    b.HasData(
                        new
                        {
                            FranchiseId = new Guid("5073af1b-9c3c-4766-ae62-f9253aaf0afb"),
                            Description = "Comic Franchise",
                            Name = "Marvel",
                            Names = "[\"marvel\",\"марвел\"]"
                        },
                        new
                        {
                            FranchiseId = new Guid("b14a485d-dca4-48b6-a524-a361bc0745e9"),
                            Description = "Comic Franchise",
                            Name = "DC",
                            Names = "[\"dc\",\"диси\",\"дс\"]"
                        },
                        new
                        {
                            FranchiseId = new Guid("515ac11d-55a1-4e4b-8364-6543cd6e6154"),
                            Description = "Manga Franchise",
                            Name = "Naruto",
                            Names = "[\"наруто\",\"naruto\"]"
                        });
                });

            modelBuilder.Entity("AniMatcher.Domain.Question", b =>
                {
                    b.Property<Guid>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TestId")
                        .HasColumnType("uuid");

                    b.HasKey("QuestionId");

                    b.HasIndex("TestId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("AniMatcher.Domain.QuestionOption", b =>
                {
                    b.Property<Guid>("QuestionOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CharacterOrder")
                        .HasColumnType("integer");

                    b.Property<Guid?>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("QuestionOptionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuestionOptions");
                });

            modelBuilder.Entity("AniMatcher.Domain.Rating", b =>
                {
                    b.Property<Guid>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<int>("Sum")
                        .HasColumnType("integer");

                    b.Property<Guid>("TestId")
                        .HasColumnType("uuid");

                    b.HasKey("RatingId");

                    b.HasIndex("TestId")
                        .IsUnique();

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("AniMatcher.Domain.Tag", b =>
                {
                    b.Property<Guid>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TagId");

                    b.HasIndex("TagName")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("AniMatcher.Domain.Test", b =>
                {
                    b.Property<Guid>("TestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<List<Guid>>("CharactersId")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<Guid>>("TagsId")
                        .HasColumnType("uuid[]");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TestId");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("CharacterTest", b =>
                {
                    b.Property<Guid>("CharactersCharacterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TestId")
                        .HasColumnType("uuid");

                    b.HasKey("CharactersCharacterId", "TestId");

                    b.HasIndex("TestId");

                    b.ToTable("CharacterTest");
                });

            modelBuilder.Entity("TagTest", b =>
                {
                    b.Property<Guid>("TagsTagId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TestId")
                        .HasColumnType("uuid");

                    b.HasKey("TagsTagId", "TestId");

                    b.HasIndex("TestId");

                    b.ToTable("TagTest");
                });

            modelBuilder.Entity("AniMatcher.Domain.Character", b =>
                {
                    b.HasOne("AniMatcher.Domain.Franchise", "Copyright")
                        .WithMany()
                        .HasForeignKey("CopyrightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Copyright");
                });

            modelBuilder.Entity("AniMatcher.Domain.Question", b =>
                {
                    b.HasOne("AniMatcher.Domain.Test", null)
                        .WithMany("Questions")
                        .HasForeignKey("TestId");
                });

            modelBuilder.Entity("AniMatcher.Domain.QuestionOption", b =>
                {
                    b.HasOne("AniMatcher.Domain.Question", null)
                        .WithMany("Options")
                        .HasForeignKey("QuestionId");
                });

            modelBuilder.Entity("AniMatcher.Domain.Rating", b =>
                {
                    b.HasOne("AniMatcher.Domain.Test", "Test")
                        .WithOne("Rating")
                        .HasForeignKey("AniMatcher.Domain.Rating", "TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Test");
                });

            modelBuilder.Entity("CharacterTest", b =>
                {
                    b.HasOne("AniMatcher.Domain.Character", null)
                        .WithMany()
                        .HasForeignKey("CharactersCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AniMatcher.Domain.Test", null)
                        .WithMany()
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TagTest", b =>
                {
                    b.HasOne("AniMatcher.Domain.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AniMatcher.Domain.Test", null)
                        .WithMany()
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AniMatcher.Domain.Question", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("AniMatcher.Domain.Test", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Rating")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
