// <auto-generated />
using System;
using System.Collections.Generic;
using AniMatcher.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AniMatcher.DataAccess.Migrations
{
    [DbContext(typeof(AniMatcherContext))]
    [Migration("20250414131337_TimeZoneChanged")]
    partial class TimeZoneChanged
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AniMatcher.Domain.Character", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CopyrightId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Names")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("CharacterId");

                    b.HasIndex("CopyrightId");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            CharacterId = new Guid("8920021e-687d-4f58-8ae4-3e3837c30da9"),
                            CopyrightId = new Guid("30cc1f7f-d383-499b-babc-e4a7e4dc8565"),
                            Name = "Batman",
                            Names = "[\"бэтмэн\",\"бэтмен\",\"batman\"]"
                        },
                        new
                        {
                            CharacterId = new Guid("8b8230ce-ccde-4ec0-bba5-b4ff2bfcc73e"),
                            CopyrightId = new Guid("30cc1f7f-d383-499b-babc-e4a7e4dc8565"),
                            Name = "Superman",
                            Names = "[\"superman\",\"супермен\",\"супермэн\"]"
                        },
                        new
                        {
                            CharacterId = new Guid("120108a0-c28c-4a23-8015-2bee4cf9fb93"),
                            CopyrightId = new Guid("30cc1f7f-d383-499b-babc-e4a7e4dc8565"),
                            Name = "Flash",
                            Names = "[\"flash\",\"флэш\"]"
                        },
                        new
                        {
                            CharacterId = new Guid("e75ec5e1-1a8a-4afc-bd9b-dd931c491015"),
                            CopyrightId = new Guid("1918fde4-57f8-4a55-b27b-310e15b7aaa3"),
                            Name = "Hulk",
                            Names = "[\"hulk\",\"халк\"]"
                        },
                        new
                        {
                            CharacterId = new Guid("0134a82f-e535-49ac-9663-dbaf34c62691"),
                            CopyrightId = new Guid("1918fde4-57f8-4a55-b27b-310e15b7aaa3"),
                            Name = "Spider Man",
                            Names = "[\"человек-паук\",\"человек паук\",\"spider-man\",\"spider man\"]"
                        },
                        new
                        {
                            CharacterId = new Guid("72436d46-9f64-4338-86c3-a2b5404f3bb5"),
                            CopyrightId = new Guid("1918fde4-57f8-4a55-b27b-310e15b7aaa3"),
                            Name = "Iron Man",
                            Names = "[\"iron man\",\"ironman\",\"железный человек\"]"
                        },
                        new
                        {
                            CharacterId = new Guid("5141b749-c57f-492a-bed9-820cc4fd4633"),
                            CopyrightId = new Guid("5dadb7d7-4f91-40af-bdc7-2c76811f60d1"),
                            Name = "Naruto",
                            Names = "[\"наруто\",\"naruto\"]"
                        },
                        new
                        {
                            CharacterId = new Guid("af9f8ca0-69c9-4f97-bded-40ed3f0066d0"),
                            CopyrightId = new Guid("5dadb7d7-4f91-40af-bdc7-2c76811f60d1"),
                            Name = "Sasuke",
                            Names = "[\"саске\",\"сасуке\",\"sasuke\"]"
                        },
                        new
                        {
                            CharacterId = new Guid("ef2f1f0a-61ca-41a1-bb7f-7fe022422826"),
                            CopyrightId = new Guid("5dadb7d7-4f91-40af-bdc7-2c76811f60d1"),
                            Name = "Sakura",
                            Names = "[\"sakura\",\"сакура\"]"
                        });
                });

            modelBuilder.Entity("AniMatcher.Domain.Franchise", b =>
                {
                    b.Property<Guid>("FranchiseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Names")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("FranchiseId");

                    b.ToTable("Franchises");

                    b.HasData(
                        new
                        {
                            FranchiseId = new Guid("1918fde4-57f8-4a55-b27b-310e15b7aaa3"),
                            Description = "Comic Franchise",
                            Name = "Marvel",
                            Names = "[\"marvel\",\"марвел\"]"
                        },
                        new
                        {
                            FranchiseId = new Guid("30cc1f7f-d383-499b-babc-e4a7e4dc8565"),
                            Description = "Comic Franchise",
                            Name = "DC",
                            Names = "[\"dc\",\"диси\",\"дс\"]"
                        },
                        new
                        {
                            FranchiseId = new Guid("5dadb7d7-4f91-40af-bdc7-2c76811f60d1"),
                            Description = "Manga Franchise",
                            Name = "Naruto",
                            Names = "[\"наруто\",\"naruto\"]"
                        });
                });

            modelBuilder.Entity("AniMatcher.Domain.Question", b =>
                {
                    b.Property<Guid>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TestId")
                        .HasColumnType("uuid");

                    b.HasKey("QuestionId");

                    b.HasIndex("TestId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("AniMatcher.Domain.QuestionOption", b =>
                {
                    b.Property<Guid>("QuestionOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CharacterOrder")
                        .HasColumnType("integer");

                    b.Property<Guid?>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("QuestionOptionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuestionOptions");
                });

            modelBuilder.Entity("AniMatcher.Domain.Rating", b =>
                {
                    b.Property<Guid>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<int>("Sum")
                        .HasColumnType("integer");

                    b.Property<Guid>("TestId")
                        .HasColumnType("uuid");

                    b.HasKey("RatingId");

                    b.HasIndex("TestId")
                        .IsUnique();

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("AniMatcher.Domain.Tag", b =>
                {
                    b.Property<Guid>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TestId")
                        .HasColumnType("uuid");

                    b.HasKey("TagId");

                    b.HasIndex("TagName")
                        .IsUnique();

                    b.HasIndex("TestId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("AniMatcher.Domain.Test", b =>
                {
                    b.Property<Guid>("TestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<List<Guid>>("CharactersId")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<Guid>>("TagsId")
                        .HasColumnType("uuid[]");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TestId");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("CharacterTest", b =>
                {
                    b.Property<Guid>("CharactersCharacterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TestId")
                        .HasColumnType("uuid");

                    b.HasKey("CharactersCharacterId", "TestId");

                    b.HasIndex("TestId");

                    b.ToTable("CharacterTest");
                });

            modelBuilder.Entity("AniMatcher.Domain.Character", b =>
                {
                    b.HasOne("AniMatcher.Domain.Franchise", "Copyright")
                        .WithMany()
                        .HasForeignKey("CopyrightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Copyright");
                });

            modelBuilder.Entity("AniMatcher.Domain.Question", b =>
                {
                    b.HasOne("AniMatcher.Domain.Test", null)
                        .WithMany("Questions")
                        .HasForeignKey("TestId");
                });

            modelBuilder.Entity("AniMatcher.Domain.QuestionOption", b =>
                {
                    b.HasOne("AniMatcher.Domain.Question", null)
                        .WithMany("Options")
                        .HasForeignKey("QuestionId");
                });

            modelBuilder.Entity("AniMatcher.Domain.Rating", b =>
                {
                    b.HasOne("AniMatcher.Domain.Test", "Test")
                        .WithOne("Rating")
                        .HasForeignKey("AniMatcher.Domain.Rating", "TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Test");
                });

            modelBuilder.Entity("AniMatcher.Domain.Tag", b =>
                {
                    b.HasOne("AniMatcher.Domain.Test", null)
                        .WithMany("Tags")
                        .HasForeignKey("TestId");
                });

            modelBuilder.Entity("CharacterTest", b =>
                {
                    b.HasOne("AniMatcher.Domain.Character", null)
                        .WithMany()
                        .HasForeignKey("CharactersCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AniMatcher.Domain.Test", null)
                        .WithMany()
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AniMatcher.Domain.Question", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("AniMatcher.Domain.Test", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Rating")
                        .IsRequired();

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
