// <auto-generated />
using System;
using AniMatcher.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AniMatcher.DataAccess.Migrations
{
    [DbContext(typeof(AniMatcherContext))]
    [Migration("20250414101324_AddedJsonNamesColumns")]
    partial class AddedJsonNamesColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AniMatcher.Domain.Character", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CopyrightId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Names")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("TestId")
                        .HasColumnType("uuid");

                    b.HasKey("CharacterId");

                    b.HasIndex("CopyrightId");

                    b.HasIndex("TestId");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            CharacterId = new Guid("f1c18faf-4487-4c3f-92cf-14beded85de3"),
                            CopyrightId = new Guid("593fbaa3-d6ea-42bd-8db7-45c4330eead7"),
                            Name = "Batman",
                            Names = "[\"бэтмэн\",\"бэтмен\",\"batman\"]"
                        },
                        new
                        {
                            CharacterId = new Guid("264e82f4-f727-4e98-84e8-ff76be3c1f80"),
                            CopyrightId = new Guid("593fbaa3-d6ea-42bd-8db7-45c4330eead7"),
                            Name = "Superman",
                            Names = "[\"superman\",\"супермен\",\"супермэн\"]"
                        },
                        new
                        {
                            CharacterId = new Guid("30432432-09a2-441e-84ff-c055e50a5914"),
                            CopyrightId = new Guid("593fbaa3-d6ea-42bd-8db7-45c4330eead7"),
                            Name = "Flash",
                            Names = "[\"flash\",\"флэш\"]"
                        },
                        new
                        {
                            CharacterId = new Guid("ac7289e8-da90-4f79-8c81-37f1ca8cb668"),
                            CopyrightId = new Guid("5ceddbd1-ee1d-49d7-a8fc-ecc259ce2ac7"),
                            Name = "Hulk",
                            Names = "[\"hulk\",\"халк\"]"
                        },
                        new
                        {
                            CharacterId = new Guid("de57e157-df96-42a6-993d-cc1458f60dd1"),
                            CopyrightId = new Guid("5ceddbd1-ee1d-49d7-a8fc-ecc259ce2ac7"),
                            Name = "Spider Man",
                            Names = "[\"человек-паук\",\"человек паук\",\"spider-man\",\"spider man\"]"
                        },
                        new
                        {
                            CharacterId = new Guid("2350f880-02f7-4e6d-a54f-97f28ec82ca3"),
                            CopyrightId = new Guid("5ceddbd1-ee1d-49d7-a8fc-ecc259ce2ac7"),
                            Name = "Iron Man",
                            Names = "[\"iron man\",\"ironman\",\"железный человек\"]"
                        },
                        new
                        {
                            CharacterId = new Guid("0d2a9901-ad20-45e1-92d4-e23ba622d255"),
                            CopyrightId = new Guid("bf5f64d4-40d5-4a47-9c8b-8fd64a788900"),
                            Name = "Naruto",
                            Names = "[\"наруто\",\"naruto\"]"
                        },
                        new
                        {
                            CharacterId = new Guid("6b4fc59c-02f5-42a6-8895-cf585f9e55c1"),
                            CopyrightId = new Guid("bf5f64d4-40d5-4a47-9c8b-8fd64a788900"),
                            Name = "Sasuke",
                            Names = "[\"саске\",\"сасуке\",\"sasuke\"]"
                        },
                        new
                        {
                            CharacterId = new Guid("02a8b588-7cbc-4f0d-a581-ca53e4bd81b8"),
                            CopyrightId = new Guid("bf5f64d4-40d5-4a47-9c8b-8fd64a788900"),
                            Name = "Sakura",
                            Names = "[\"sakura\",\"сакура\"]"
                        });
                });

            modelBuilder.Entity("AniMatcher.Domain.Franchise", b =>
                {
                    b.Property<Guid>("FranchiseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Names")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("TestId")
                        .HasColumnType("uuid");

                    b.HasKey("FranchiseId");

                    b.HasIndex("TestId");

                    b.ToTable("Franchises");

                    b.HasData(
                        new
                        {
                            FranchiseId = new Guid("5ceddbd1-ee1d-49d7-a8fc-ecc259ce2ac7"),
                            Description = "Comic Franchise",
                            Name = "Marvel",
                            Names = "[\"marvel\",\"марвел\"]"
                        },
                        new
                        {
                            FranchiseId = new Guid("593fbaa3-d6ea-42bd-8db7-45c4330eead7"),
                            Description = "Comic Franchise",
                            Name = "DC",
                            Names = "[\"dc\",\"диси\",\"дс\"]"
                        },
                        new
                        {
                            FranchiseId = new Guid("bf5f64d4-40d5-4a47-9c8b-8fd64a788900"),
                            Description = "Manga Franchise",
                            Name = "Naruto",
                            Names = "[\"наруто\",\"naruto\"]"
                        });
                });

            modelBuilder.Entity("AniMatcher.Domain.Question", b =>
                {
                    b.Property<Guid>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TestId")
                        .HasColumnType("uuid");

                    b.HasKey("QuestionId");

                    b.HasIndex("TestId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("AniMatcher.Domain.QuestionOption", b =>
                {
                    b.Property<Guid>("QuestionOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CharacterOrder")
                        .HasColumnType("integer");

                    b.Property<Guid?>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("QuestionOptionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuestionOptions");
                });

            modelBuilder.Entity("AniMatcher.Domain.Rating", b =>
                {
                    b.Property<Guid>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<int>("Sum")
                        .HasColumnType("integer");

                    b.Property<Guid>("TestId")
                        .HasColumnType("uuid");

                    b.HasKey("RatingId");

                    b.HasIndex("TestId")
                        .IsUnique();

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("AniMatcher.Domain.Tag", b =>
                {
                    b.Property<Guid>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TestId")
                        .HasColumnType("uuid");

                    b.HasKey("TagId");

                    b.HasIndex("TestId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("AniMatcher.Domain.Test", b =>
                {
                    b.Property<Guid>("TestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TestId");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("AniMatcher.Domain.Character", b =>
                {
                    b.HasOne("AniMatcher.Domain.Franchise", "Copyright")
                        .WithMany()
                        .HasForeignKey("CopyrightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AniMatcher.Domain.Test", null)
                        .WithMany("Characters")
                        .HasForeignKey("TestId");

                    b.Navigation("Copyright");
                });

            modelBuilder.Entity("AniMatcher.Domain.Franchise", b =>
                {
                    b.HasOne("AniMatcher.Domain.Test", null)
                        .WithMany("Franchises")
                        .HasForeignKey("TestId");
                });

            modelBuilder.Entity("AniMatcher.Domain.Question", b =>
                {
                    b.HasOne("AniMatcher.Domain.Test", null)
                        .WithMany("Questions")
                        .HasForeignKey("TestId");
                });

            modelBuilder.Entity("AniMatcher.Domain.QuestionOption", b =>
                {
                    b.HasOne("AniMatcher.Domain.Question", null)
                        .WithMany("Options")
                        .HasForeignKey("QuestionId");
                });

            modelBuilder.Entity("AniMatcher.Domain.Rating", b =>
                {
                    b.HasOne("AniMatcher.Domain.Test", "Test")
                        .WithOne("Rating")
                        .HasForeignKey("AniMatcher.Domain.Rating", "TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Test");
                });

            modelBuilder.Entity("AniMatcher.Domain.Tag", b =>
                {
                    b.HasOne("AniMatcher.Domain.Test", null)
                        .WithMany("Tags")
                        .HasForeignKey("TestId");
                });

            modelBuilder.Entity("AniMatcher.Domain.Question", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("AniMatcher.Domain.Test", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("Franchises");

                    b.Navigation("Questions");

                    b.Navigation("Rating")
                        .IsRequired();

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
