version: '3.8'

services:
  animatcher.api:
    container_name: animatcher.api
    image: animatcherimage
    build:
      context: .
      dockerfile: AniMatcher.Api/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:81;http://+:443
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__PostgresConnection=Host=postgres_db;Port=5432;Database=animatcherdb;Username=postgres;Password=password@123
    ports:
      - "8000:81"
      - "8001:443"
    depends_on:
      - postgres

  postgres:
    container_name: postgres_db
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: password@123

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin_password
    ports:
      - "5050:80"
    depends_on:
      - postgres